# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('single', models.CharField(max_length=200)),
                ('multiple', models.CharField(max_length=200)),
                ('looking', models.CharField(max_length=500)),
                ('hear', models.CharField(max_length=500)),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packaged', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('variety', models.CharField(max_length=100)),
                ('lot', models.CharField(max_length=100)),
                ('units', models.CharField(max_length=100)),
                ('storage', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('ava', models.CharField(max_length=100)),
                ('alc', models.CharField(max_length=100)),
                ('chemanalysis', models.CharField(max_length=100)),
                ('current', models.CharField(max_length=500)),
                ('pending', models.CharField(max_length=500)),
                ('other', models.CharField(max_length=500)),
                ('promised', models.CharField(max_length=500)),
                ('available', models.CharField(max_length=500)),
                ('comments', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('single', models.CharField(max_length=200)),
                ('multiple', models.CharField(max_length=200)),
                ('looking', models.CharField(max_length=500)),
                ('hear', models.CharField(max_length=500)),
                ('requestedwine', models.TextField()),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
