# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wineobjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='review_date',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
